### ISSUE TITLE
Lol Scoreboard Problem

### ISSUE THREAD

**Issue by ther3y3s** [c4ldas/streamelements-widgets#23] opened 2024-07-01 11:53 UTC
Hi, i'm trying to install this widget. 

I install the certificate following this method by chatgpt: 
Open "Certificate Manager" by typing certmgr.msc in the Start menu.
Go to the "Trusted Root Certification Authorities" folder and click on "Certificates".
Right-click on "Certificates" and select "All Assets" > "Import".
Follow the import wizard, selecting the riotgames.pem file and completing the import.

Or this one find online:
2. Open your command promt as administrator
3. Type command : certutil.exe -addstore root %path_to_certificate%

But, after i setup obs like you write, still no gama info when i start a custom game to test the widget. How i can fix it?

**Comment by c4ldas** [comment] 2024-07-01 15:23
Yeah, sorry, the README with the instructions for installation is still incomplete, let me review and update it. Will let you know once it is done.

**Comment by ther3y3s** [comment] 2024-07-01 17:59
Ah okok, i think the only problem was how to run the certificate. Thanks for all

**Comment by c4ldas** [comment] 2024-07-01 20:08
The documentation is now updated, and the way you imported the certificate seems to be valid, however, I'd rather install the certificate using certutils as a normal user, not admin. 

But one important thing is to update the OBS shortcut, adding `--disable-web-security` to the target, like the image: 

![image](https://github.com/c4ldas/streamelements-widgets/assets/75918726/a43a1113-22e1-4919-8fde-b4efd94466d9)

If still not working, please let me know and we can check other options.

**Comment by c4ldas** [comment] 2024-07-02 16:41
Closing issue after confirmed widget is working as expected

**Closed by c4ldas** 2024-07-02 16:41 UTC
Labels: documentation
